add how-to-add-samba-vfs-module.md
opencurve/curve-meetup-slides pull request #57
Opened 2023-01-09 09:48 UTC by h0hmj

add "how to add a samba vfs module"

Signed-off-by: h0hmj <h0hmjcn@gmail.com>

2023-01-09 11:34 UTC, aspirer commented
加点curvefs相关的内容啊，主要目的是介绍curvefs支持smb协议的具体方案（怎么配置、怎么挂载使用、怎么支持多用户之类的），介绍自定义扩展vfs module是次要内容了。

2023-01-09 11:37 UTC, aspirer requested changes
参考评论补充下curvefs相关内容哈

2023-01-10 02:02 UTC, aspirer commented
## Curve共享文件存储介绍
Curve共享文件存储（简称CurveFS）是Curve社区开发的新一代分布式共享文件存储系统，在网易内部已有PB级规模应用，其核心架构可以参考设计文档：https://github.com/opencurve/curve/blob/master/docs/cn/curvefs_architecture.md

相比传统的分布式文件系统，CurveFS具备如下几个特色：
1. 支持将文件数据存储到对象存储和CurveBS块存储上，可以做到冷热数据分层存储和生命周期管理（roadmap），数据容量可无限扩展
2. 基于multi-raft支持元数据的分区存储，具备无限扩展性，性能可随节点数线性扩展，不存在性能热点问题
3. 针对AI训练/机器学习场景、elasticsearch/clickhouse/starrocks等大数据场景做了专门优化，支持内存缓存、本地磁盘缓存、分布式内存缓存（基于memcached或其他kv存储）等多级缓存，可对文件读写进行缓存加速并保持数据写入可靠性，支持数据预热到缓存中加速读取过程

2023-01-29 02:23 UTC, aspirer approved these changes

2023-01-29 03:12 UTC, ilixiaocui approved these changes

2023-01-29 03:12 UTC, merged